ci: edit pre-commit script to ban direct main commits

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,2 +1,8 @@
 #!/usr/bin/env sh
+CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
+echo "$CURRENT_BRANCH"
+if [ "$CURRENT_BRANCH" = "main" ]; then
+    echo "Cannot commit directly to main!"
+    exit 1
+fi
 pnpm lint-staged
